#!/bin/bash
# QUICK_PARAMETER_TUNING.sh
# Shows examples of how to run parameter tuning experiments

cd "$(dirname "$0")"

echo "╔════════════════════════════════════════════════════════════════════════════════╗"
echo "║         RTT-Trend-Aware CUBIC - Parameter Tuning Quick Reference               ║"
echo "╚════════════════════════════════════════════════════════════════════════════════╝"
echo ""

echo "1. RUN WITH DEFAULT PARAMETERS (baseline)"
echo "   ./ns3 run scratch/test-cubic-comparison > comparison_baseline.dat"
echo "   .venv/bin/python3 plot-rtt-comparison.py"
echo ""

echo "2. RUN WITH DIFFERENT K VALUES (sensitivity)"
echo "   # More conservative:"
echo "   ./ns3 run scratch/test-cubic-comparison -- --K=0.25 > comparison_K0.25.dat"
echo ""
echo "   # More aggressive:"
echo "   ./ns3 run scratch/test-cubic-comparison -- --K=1.0 > comparison_K1.0.dat"
echo ""

echo "3. RUN WITH DIFFERENT ALPHA VALUES (RTT smoothing)"
echo "   # More responsive to RTT changes:"
echo "   ./ns3 run scratch/test-cubic-comparison -- --Alpha=0.25 > comparison_alpha0.25.dat"
echo ""
echo "   # Smoother RTT estimates:"
echo "   ./ns3 run scratch/test-cubic-comparison -- --Alpha=0.0625 > comparison_alpha0.0625.dat"
echo ""

echo "4. RUN WITH NARROW GAMMA BOUNDS (conservative)"
echo "   ./ns3 run scratch/test-cubic-comparison -- --GammaMin=0.7 --GammaMax=1.3 > comparison_narrow.dat"
echo ""

echo "5. RUN WITH WIDE GAMMA BOUNDS (aggressive)"
echo "   ./ns3 run scratch/test-cubic-comparison -- --GammaMin=0.3 --GammaMax=2.0 > comparison_wide.dat"
echo ""

echo "6. RUN ALL COMBINATIONS (automated sweep)"
echo "   chmod +x run-parameter-sweep.py"
echo "   ./run-parameter-sweep.py --k 0.25 0.5 1.0 --alpha 0.0625 0.125 0.25"
echo ""

echo "══════════════════════════════════════════════════════════════════════════════════"
echo ""
echo "COMPARISON WORKFLOW"
echo "───────────────────"
echo ""
echo "Step 1: Get baseline"
echo "  ./ns3 run scratch/test-cubic-comparison > comparison_baseline.dat"
echo "  .venv/bin/python3 plot-rtt-comparison.py"
echo "  → Saves: comparison-cwnd-single.png, comparison-rtt-gamma.png"
echo "  → Print stats and look for:"
echo "    - Flow 3 (RTT-Aware) mean CWND vs Flow 1 (Original)"
echo "    - Gamma statistics (should NOT be all 1.0)"
echo ""
echo "Step 2: Modify one parameter"
echo "  ./ns3 run scratch/test-cubic-comparison -- --K=1.0 > comparison_K1.0.dat"
echo "  .venv/bin/python3 plot-rtt-comparison.py"
echo "  → Move outputs: mv comparison-*.png results_K1.0/"
echo ""
echo "Step 3: Compare visually"
echo "  # Open both result directories and compare:"
echo "  # - comparison-cwnd-single.png (should see more variation in RTT-Aware)"
echo "  # - comparison-rtt-gamma.png (gamma should vary, not stuck at 1.0)"
echo ""
echo "Step 4: Check console output for statistics"
echo "  # Look for:"
echo "  #   Flow 1 (Original): mean=185.7 pkts"
echo "  #   Flow 3 (RTT-Aware): mean=138.2 pkts"
echo "  #   Difference indicates aggressiveness of adjustment"
echo ""

echo "══════════════════════════════════════════════════════════════════════════════════"
echo ""
echo "TROUBLESHOOTING"
echo "───────────────"
echo ""
echo "Q: Gamma is always 1.0 (no adjustment happening)"
echo "A: Check comparison-rtt-gamma.png top subplot:"
echo "   - Does RTT actually vary? If flat at 100ms, RTT tracking not working"
echo "   - Try increasing K or Alpha to see if that helps"
echo ""
echo "Q: Original CUBIC and RTT-Aware are identical"
echo "A: - Increase K (make adjustment more aggressive)"
echo "     ./ns3 run scratch/test-cubic-comparison -- --K=1.5"
echo "   - Or lower Alpha (cleaner RTT signal)"
echo "     ./ns3 run scratch/test-cubic-comparison -- --Alpha=0.0625"
echo ""
echo "Q: RTT-Aware CWND oscillates wildly"
echo "A: - Decrease K (reduce adjustment sensitivity)"
echo "     ./ns3 run scratch/test-cubic-comparison -- --K=0.25"
echo "   - Or narrow gamma bounds (limit max adjustment)"
echo "     ./ns3 run scratch/test-cubic-comparison -- --GammaMin=0.75 --GammaMax=1.25"
echo ""
echo "Q: Gamma bounces between extremes (0.5 and 1.5)"
echo "A: - Increase Alpha (smoother RTT estimate)"
echo "     ./ns3 run scratch/test-cubic-comparison -- --Alpha=0.25"
echo "   - Or narrow gamma bounds"
echo ""

echo "══════════════════════════════════════════════════════════════════════════════════"
echo ""
echo "Read TUNING_GUIDE.md for comprehensive Parameter effects and formulas"
echo ""
